services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ozbio
      POSTGRES_USER: ozbio
      POSTGRES_PASSWORD: ozbio
    volumes:
      - ozbio_pg_data:/var/lib/postgresql/data

volumes:
  ozbio_pg_data:
